services:
  mongodb:
    image: mongo:7.0
    container_name: inatel-api-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: inatel_api
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - inatel-network
  mongodb-test:
    image: mongo:7.0
    container_name: inatel-api-mongodb-test
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: inatel_api_test
    volumes:
      - mongodb_test_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - inatel-network
    profiles:
      - test

  mongo-express:
    image: mongo-express:latest
    container_name: inatel-api-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongodb
    networks:
      - inatel-network
    profiles:
      - admin

volumes:
  mongodb_data:
    driver: local
  mongodb_test_data:
    driver: local

networks:
  inatel-network:
    driver: bridge
